import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";
import { Header } from "@/sections/Header";

const neuemontreal = localFont({
  src: [
    {
      path: "./font/ppneuemontreal-medium.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./font/ppneuemontreal-bold.otf",
      weight: "700",
      style: "bold",
    },
  ],
  variable: "--font-neuemontreal",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${neuemontreal.variable} antialiased font-neuemontreal`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
